# -*- coding: utf-8 -*-
"""aula03sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLuBfIQBNEtWRS8PfjEoNyZkWAlM-6L1
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVIS
# ESTUDANTE: VICTOR

print ('Ola, ETE PORTO DIGITAL')